image: ruby:2.5

test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get upgrade -y
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -
  - apt-get install -y nodejs
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  - apt-get install -y yarn
  - rm -f Gemfile.lock
  - bundle install --path /cache
  - RAILS_ENV=test bundle exec rails webpacker:compile
  - rails webpacker:install
  - bundle exec rake db:create
  - bundle exec rake test

staging:
  stage: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=gitlab-ci-ruby-test-staging --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master

production:
  stage: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=gitlab-ci-ruby-test-prod --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - tags
